services:
  mynginx-volume-c:
    image: nginx:alpine-slim
    ports:
      - 880:80
    # method 1
    # command: ["sh", "-c", "echo 1", "echo 22"]

    # method 2
    command: |
      sh -c 'echo 1 ; echo 22'
