name: cilong_buildimage_ongitpush


on: 
  push:
    branches: [ci/long-build]
  workflow_dispatch:

jobs:
  deploy_job:
    runs-on: ubuntu-22.04
    steps:

    - name: check date
      run: |
        date
        echo TODO ci/long build
