name: citung_dispatch

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-22.04
    steps:
      - name: Check date
        run: date

  job2:
    runs-on: ubuntu-22.04
    steps:
      - name: Print out something
        run: echo 12345
